### ISSUE TITLE
Can Anyone take a look at this? Probably some configuration issue.

### ISSUE THREAD

**Issue by viggi-v** [Hrily/SimOS#13]
$ python server.py
 * Running on http://127.0.0.1:8000/ (Press CTRL+C to quit)
[2017-04-21 22:45:12,331] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Program Files\Miniconda3\lib\site-packages\flask\app.py", line 1982,                                                                                                                 in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Miniconda3\lib\site-packages\flask\app.py", line 1614,                                                                                                                 in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Miniconda3\lib\site-packages\flask\app.py", line 1517,                                                                                                                 in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Miniconda3\lib\site-packages\flask\_compat.py", line 33                                                                                                                , in reraise
    raise value
  File "C:\Program Files\Miniconda3\lib\site-packages\flask\app.py", line 1612,                                                                                                                 in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Miniconda3\lib\site-packages\flask\app.py", line 1598,                                                                                                                 in dispatch_request
user@JARVIS MINGW64 /e/testing/SimOS (master)(**req.view_args)
$ File "server.py", line 223, in page_home
    shell.init()
  File "E:\testing\SimOS\shell.py", line 12, in init
    p = Popen(['./file_system/file_system'], stdin=PIPE, stdout=PIPE)
  File "C:\Program Files\Miniconda3\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Miniconda3\lib\subprocess.py", line 1224, in _execute_c                                                                                                                hild
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application
127.0.0.1 - - [21/Apr/2017 22:45:12] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [21/Apr/2017 22:45:13] "GET /favicon.ico HTTP/1.1" 404 -
[2017-04-21 22:45:24,136] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Program Files\Miniconda3\lib\site-packages\flask\app.py", line 1982,                                                                                                                 in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Program Files\Miniconda3\lib\site-packages\flask\app.py", line 1614,                                                                                                                 in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Program Files\Miniconda3\lib\site-packages\flask\app.py", line 1517,                                                                                                                 in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Program Files\Miniconda3\lib\site-packages\flask\_compat.py", line 33                                                                                                                , in reraise
    raise value
  File "C:\Program Files\Miniconda3\lib\site-packages\flask\app.py", line 1612,                                                                                                                 in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Program Files\Miniconda3\lib\site-packages\flask\app.py", line 1598,                                                                                                                 in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "server.py", line 223, in page_home
    shell.init()
  File "E:\testing\SimOS\shell.py", line 12, in init
    p = Popen(['./file_system/file_system'], stdin=PIPE, stdout=PIPE)
  File "C:\Program Files\Miniconda3\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\Miniconda3\lib\subprocess.py", line 1224, in _execute_c                                                                                                                hild
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application
127.0.0.1 - - [21/Apr/2017 22:45:24] "GET / HTTP/1.1" 500 -
127.0.0.1 - - [21/Apr/2017 22:45:24] "GET /favicon.ico HTTP/1.1" 404 -

**Comment by Hrily** [comment]
@viggi-v 

> OSError: [WinError 193] %1 is not a valid Win32 application

I'm Sorry :(
This was made on Linux platform and is not currently supported on Windows platform.
